USE [DataHub]
GO

CREATE FUNCTION [dbo].[GetReporteeHierarchy] (@EmployeeId [nvarchar](50), @Level [int])
RETURNS TABLE
AS

RETURN
WITH Reportees (
     [Level],
     empNo,
     userID,
     fname,
     lname,
     middleName,
     preferredName,
     FullName,
     mainWorkAddressStreet,
     mainWorkAddressPostCode,
     mainWorkAddresssuburbCity,
     mainWorkAddressStateTerritory,
     mainWorkAddressCountry,
     nominatedMailingAddressStreet,
     nominatedMailingAddressPostcode,
     nominatedMailingAddressSuburbCity,
     nominatedMailingAddressStateTerritory,
     nominatedMailingAddressCountry,
     telephoneNo,
     mobileNo,
     emailAddress,
     homeTelephoneNo,
     homeMobileNo,
     businessUnit,
     personnelArea,
     personnelSubArea,
     empGroup,
     empSubGroup,
     contractType,
     employmentInstrument,
     costCentre,
     OneUpEmployeeNo,
     dateCommencedInPosition,
     positionNo,
     positionTitle,
     hrOrgUnit,
     jobCode,
     workCode,
     jobTitle,
     band
) 
AS
(
    -- Anchor member definition
    SELECT 0 AS [Level],
           e.empNo,
           e.userID,
           e.fname,
           e.lname,
           e.middleName,
           e.preferredName,
           e.FullName,
           e.mainWorkAddressStreet,
           e.mainWorkAddressPostCode,
           e.mainWorkAddresssuburbCity,
           e.mainWorkAddressStateTerritory,
           e.mainWorkAddressCountry,
           e.nominatedMailingAddressStreet,
           e.nominatedMailingAddressPostcode,
           e.nominatedMailingAddressSuburbCity,
           e.nominatedMailingAddressStateTerritory,
           e.nominatedMailingAddressCountry,
           e.telephoneNo,
           e.mobileNo,
           e.emailAddress,
           e.homeTelephoneNo,
           e.homeMobileNo,
           e.businessUnit,
           e.personnelArea,
           e.personnelSubArea,
           e.empGroup,
           e.empSubGroup,
           e.contractType,
           e.employmentInstrument,
           e.costCentre,
           e.OneUpEmployeeNo,
           e.dateCommencedInPosition,
           e.positionNo,
           e.positionTitle,
           e.hrOrgUnit,
           e.jobCode,
           e.workCode,
           e.jobTitle,
           e.band
    FROM   dbo.Employee AS e
    WHERE  e.empNo = @EmployeeId
    UNION ALL
    -- Recursive member definition
    SELECT r.[Level] + 1,
           e.empNo,
           e.userID,
           e.fname,
           e.lname,
           e.middleName,
           e.preferredName,
           e.FullName,
           e.mainWorkAddressStreet,
           e.mainWorkAddressPostCode,
           e.mainWorkAddresssuburbCity,
           e.mainWorkAddressStateTerritory,
           e.mainWorkAddressCountry,
           e.nominatedMailingAddressStreet,
           e.nominatedMailingAddressPostcode,
           e.nominatedMailingAddressSuburbCity,
           e.nominatedMailingAddressStateTerritory,
           e.nominatedMailingAddressCountry,
           e.telephoneNo,
           e.mobileNo,
           e.emailAddress,
           e.homeTelephoneNo,
           e.homeMobileNo,
           e.businessUnit,
           e.personnelArea,
           e.personnelSubArea,
           e.empGroup,
           e.empSubGroup,
           e.contractType,
           e.employmentInstrument,
           e.costCentre,
           e.OneUpEmployeeNo,
           e.dateCommencedInPosition,
           e.positionNo,
           e.positionTitle,
           e.hrOrgUnit,
           e.jobCode,
           e.workCode,
           e.jobTitle,
           e.band
    FROM   dbo.Employee AS e
    INNER  JOIN Reportees AS r
    ON     e.OneUpEmployeeNo = r.EmpNo
    WHERE  r.[Level] < @Level
)
-- Statement that executes the CTE
SELECT e.empNo,
       e.userID,
       e.fname,
       e.lname,
       e.middleName,
       e.preferredName,
       e.FullName,
       e.mainWorkAddressStreet,
       e.mainWorkAddressPostCode,
       e.mainWorkAddresssuburbCity,
       e.mainWorkAddressStateTerritory,
       e.mainWorkAddressCountry,
       e.nominatedMailingAddressStreet,
       e.nominatedMailingAddressPostcode,
       e.nominatedMailingAddressSuburbCity,
       e.nominatedMailingAddressStateTerritory,
       e.nominatedMailingAddressCountry,
       e.telephoneNo,
       e.mobileNo,
       e.emailAddress,
       e.homeTelephoneNo,
       e.homeMobileNo,
       e.businessUnit,
       e.personnelArea,
       e.personnelSubArea,
       e.empGroup,
       e.empSubGroup,
       e.contractType,
       e.employmentInstrument,
       e.costCentre,
       e.OneUpEmployeeNo,
       e.dateCommencedInPosition,
       e.positionNo,
       e.positionTitle,
       e.hrOrgUnit,
       e.jobCode,
       e.workCode,
       e.jobTitle,
       e.band
FROM   Reportees e
WHERE  e.[Level] > 0;
GO
