
CREATE TABLE [dbo].[CEOLT_Jobs_File](
	[Job code] [float] NULL,
	[Work code] [nvarchar](255) NULL,
	[Job title] [nvarchar](255) NULL,
	[Job family] [float] NULL,
	[Job family name] [nvarchar](255) NULL,
	[Job group] [nvarchar](255) NULL,
	[Job group name] [nvarchar](255) NULL,
	[Band] [nvarchar](255) NULL,
	[Customer facing group] [nvarchar](255) NULL,
	[Contributor] [nvarchar](255) NULL
);
GO


CREATE TABLE [dbo].[PEX_REF_ORG](
	[ouID] [nvarchar](50) NULL,
	[startDate] [datetime] NULL,
	[endDate] [datetime] NULL,
	[PARENTOuID] [nvarchar](50) NULL,
	[telOuID] [nvarchar](50) NULL,
	[telStartDate] [datetime] NULL,
	[telEndDate] [datetime] NULL,
	[telParentOuID] [nvarchar](50) NULL,
	[buOuID] [nvarchar](50) NULL,
	[buStartDate] [datetime] NULL,
	[buEndDate] [datetime] NULL,
	[buParentOuID] [nvarchar](50) NULL,
	[lob1OuID] [nvarchar](50) NULL,
	[lob1StartDate] [datetime] NULL,
	[lob1EndDate] [datetime] NULL,
	[lob1ParentOuID] [nvarchar](50) NULL,
	[lob2OuID] [nvarchar](50) NULL,
	[lob2StartDate] [datetime] NULL,
	[lob2EndDate] [datetime] NULL,
	[lob2ParentOuID] [nvarchar](50) NULL,
	[lob3OuID] [nvarchar](50) NULL,
	[lob3StartDate] [datetime] NULL,
	[lob3EndDate] [datetime] NULL,
	[lob3ParentOuID] [nvarchar](50) NULL,
	[lob4OuID] [nvarchar](50) NULL,
	[lob4StartDate] [datetime] NULL,
	[lob4EndDate] [datetime] NULL,
	[lob4ParentOuID] [nvarchar](50) NULL,
	[lob5OuID] [nvarchar](50) NULL,
	[lob5StartDate] [datetime] NULL,
	[lob5EndDate] [datetime] NULL,
	[lob5ParentOuID] [nvarchar](50) NULL,
	[lob6OuID] [nvarchar](50) NULL,
	[lob6StartDate] [datetime] NULL,
	[lob6EndDate] [datetime] NULL,
	[lob6ParentOuID] [nvarchar](50) NULL,
	[lob7OuID] [nvarchar](50) NULL,
	[lob7StartDate] [datetime] NULL,
	[lob7EndDate] [datetime] NULL,
	[lob7ParentOuID] [nvarchar](50) NULL,
	[lob8OuID] [nvarchar](50) NULL,
	[lob8StartDate] [datetime] NULL,
	[lob8EndDate] [datetime] NULL,
	[lob8ParentOuID] [nvarchar](50) NULL,
	[lob9OuID] [nvarchar](50) NULL,
	[lob9StartDate] [datetime] NULL,
	[lob9EndDate] [datetime] NULL,
	[lob9ParentOuID] [nvarchar](50) NULL,
	[lob10OuID] [nvarchar](50) NULL,
	[lob10StartDate] [datetime] NULL,
	[lob10EndDate] [datetime] NULL,
	[lob10ParentOuID] [nvarchar](50) NULL,
	[lob11OuID] [nvarchar](50) NULL,
	[lob11StartDate] [datetime] NULL,
	[lob11EndDate] [datetime] NULL,
	[lob11ParentOuID] [nvarchar](50) NULL,
	[lob12OuID] [nvarchar](50) NULL,
	[lob12StartDate] [datetime] NULL,
	[lob12EndDate] [datetime] NULL,
	[lob12ParentOuID] [nvarchar](50) NULL,
	[lob13OuID] [nvarchar](50) NULL,
	[lob13StartDate] [datetime] NULL,
	[lob13EndDate] [datetime] NULL,
	[lob13ParentOuID] [nvarchar](50) NULL,
	[ssuStatus] [nvarchar](255) NULL,
	[DEPTH] [int] NULL,
	[pathID] [nvarchar](4000) NULL,
	[pathName] [nvarchar](4000) NULL
);
GO

CREATE TABLE [dbo].[PEX_REF_ORG_NAME](
	[objid] [varchar](50) NULL,
	[startDate] [datetime] NULL,
	[endDate] [datetime] NULL,
	[name] [varchar](2000) NULL,
	[objectType] [nvarchar](50) NULL,
	[planningStatus] [nvarchar](50) NULL,
	[changedOn] [datetime] NULL
);
GO

CREATE TABLE [dbo].[PEX_REF_ORG_REL](
	[objid] [nvarchar](50) NULL,
	[startDate] [datetime] NULL,
	[endDate] [datetime] NULL,
	[changedOn] [datetime] NULL,
	[relObjid] [nvarchar](50) NULL
);
GO

CREATE TABLE [dbo].[PEX_DAT_SSNSFull] (
  [reportingDate]                         [datetime] NULL,
  [empNo]                                 [nvarchar](255) NULL,
  [lName]                                 [nvarchar](255) NULL,
  [fName]                                 [nvarchar](255) NULL,
  [preferredName]                         [nvarchar](255) NULL,
  [gender]                                [nvarchar](255) NULL,
  [empGroup]                              [nvarchar](255) NULL,
  [empSubGroup]                           [nvarchar](255) NULL,
  [personnelArea]                         [nvarchar](255) NULL,
  [personnelSubArea]                      [nvarchar](255) NULL,
  [payrollArea]                           [nvarchar](255) NULL,
  [employmentInstrument]                  [nvarchar](255) NULL,
  [prescribedFNHours]                     [float] NULL,
  [FTE]                                   [float] NULL,
  [payScaleGroup]                         [nvarchar](255) NULL,
  [payScaleLevel]                         [nvarchar](255) NULL,
  [fixedRemuneration]                     [float] NULL,
  [currency]                              [nvarchar](255) NULL,
  [compaRatio]                            [float] NULL,
  [targetIncentivePercentage]             [float] NULL,
  [targetIncentiveDollar]                 [float] NULL,
  [totalRemuneration]                     [float] NULL,
  [grandfatherAllowance]                  [float] NULL,
  [additionalOningPaymentAmount]          [float] NULL,
  [additionalOningPaymentsStartDate]      [datetime] NULL,
  [additionalOningPaymentsEndDate]        [datetime] NULL,
  [principalDisability]                   [nvarchar](255) NULL,
  [firstLanguageSpoken]                   [nvarchar](255) NULL,
  [diversityDisability]                   [nvarchar](255) NULL,
  [diversityCALD]                         [nvarchar](255) NULL,
  [diversityABTSI]                        [nvarchar](255) NULL,
  [diversityGLBTI]                        [nvarchar](255) NULL,
  [superannuationScheme]                  [nvarchar](255) NULL,
  [performanceRatinneYearA]               [nvarchar](255) NULL,
  [performanceRatingTwoYearsA]            [nvarchar](255) NULL,
  [leadershipRatingTwoYearsA]             [nvarchar](255) NULL,
  [finalCombinedRatingTwoYearsA]          [nvarchar](255) NULL,
  [performanceRatingThreeYearsA]          [nvarchar](255) NULL,
  [leadershipRatingThreeYearsA]           [nvarchar](255) NULL,
  [finalCombinedRatingThreeYearsA]        [nvarchar](255) NULL,
  [dob]                                   [datetime] NULL,
  [ageYears]                              [float] NULL,
  [commencementDate]                      [datetime] NULL,
  [serviceYears]                          [float] NULL,
  [serviceAnniversaryDate]                [datetime] NULL,
  [serviceAwardDate]                      [datetime] NULL,
  [fixedTermAndContractorEndDates]        [datetime] NULL,
  [longTermLeaveFlag]                     [nvarchar](255) NULL,
  [longTermLeaveStartDate]                [datetime] NULL,
  [longTermLeaveEndDate]                  [datetime] NULL,
  [lslBalanceDays]                        [float] NULL,
  [annualLeaveBalanceDays]                [float] NULL,
  [personalLeaveBalanceDays]              [float] NULL,
  [telstraCompany]                        [nvarchar](255) NULL,
  [telstraCompanyName]                    [nvarchar](255) NULL,
  [businessUnit]                          [nvarchar](255) NULL,
  [businessUnitName]                      [nvarchar](255) NULL,
  [LOB1]                                  [nvarchar](255) NULL,
  [LOB1Name]                              [nvarchar](255) NULL,
  [LOB2]                                  [nvarchar](255) NULL,
  [LOB2Name]                              [nvarchar](255) NULL,
  [LOB3]                                  [nvarchar](255) NULL,
  [LOB3Name]                              [nvarchar](255) NULL,
  [LOB4]                                  [nvarchar](255) NULL,
  [LOB4Name]                              [nvarchar](255) NULL,
  [LOB5]                                  [nvarchar](255) NULL,
  [LOB5Name]                              [nvarchar](255) NULL,
  [LOB6]                                  [nvarchar](255) NULL,
  [LOB6Name]                              [nvarchar](255) NULL,
  [LOB7]                                  [nvarchar](255) NULL,
  [LOB7Name]                              [nvarchar](255) NULL,
  [LOB8]                                  [nvarchar](255) NULL,
  [LOB8Name]                              [nvarchar](255) NULL,
  [LOB9]                                  [nvarchar](255) NULL,
  [LOB9Name]                              [nvarchar](255) NULL,
  [LOB10]                                 [nvarchar](255) NULL,
  [LOB10Name]                             [nvarchar](255) NULL,
  [hrOrgUnit]                             [nvarchar](255) NULL,
  [hrOrgUnitname]                         [nvarchar](255) NULL,
  [dateCommencedInBu]                     [datetime] NULL,
  [lengthOfTimeInBuYears]                 [float] NULL,
  [businessUnitCostCentre]                [nvarchar](255) NULL,
  [LOB1CostCentre]                        [nvarchar](255) NULL,
  [LOB2CostCentre]                        [nvarchar](255) NULL,
  [LOB3CostCentre]                        [nvarchar](255) NULL,
  [LOB4CostCentre]                        [nvarchar](255) NULL,
  [LOB5CostCentre]                        [nvarchar](255) NULL,
  [LOB6CostCentre]                        [nvarchar](255) NULL,
  [LOB7CostCentre]                        [nvarchar](255) NULL,
  [LOB8CostCentre]                        [nvarchar](255) NULL,
  [LOB9CostCentre]                        [nvarchar](255) NULL,
  [LOB10CostCentre]                       [nvarchar](255) NULL,
  [LOB11CostCentre]                       [nvarchar](255) NULL,
  [costCentre]                            [nvarchar](255) NULL,
  [costCentreDescription]                 [nvarchar](255) NULL,
  [costCentreOveride]                     [nvarchar](255) NULL,
  [costCentreOverideName]                 [nvarchar](255) NULL,
  [activityType]                          [nvarchar](255) NULL,
  [submitsTimesheets]                     [nvarchar](255) NULL,
  [ssuStatus]                             [nvarchar](255) NULL,
  [jobCode]                               [nvarchar](255) NULL,
  [workCode]                              [nvarchar](255) NULL,
  [jobTitle]                              [nvarchar](255) NULL,
  [specialisation]                        [nvarchar](255) NULL,
  [workcodeSpecialisation]                [nvarchar](255) NULL,
  [band]                                  [nvarchar](255) NULL,
  [jobGroup]                              [nvarchar](255) NULL,
  [customerFacingGroup]                   [nvarchar](255) NULL,
  [dateCommencedInBand]                   [datetime] NULL,
  [lengthOfTimeInBandYears]               [float] NULL,
  [tempAssignWorkCode]                    [nvarchar](255) NULL,
  [tempAssignWorkCodeEndDate]             [datetime] NULL,
  [positionNo]                            [nvarchar](255) NULL,
  [positionTitle]                         [nvarchar](255) NULL,
  [dateCommencedInPosition]               [datetime] NULL,
  [lengthOfTimeInPositionYears]           [float] NULL,
  [NoOfDirectReports]                     [float] NULL,
  [icOrPL]                                [nvarchar](255) NULL,
  [OneUpEmployeeNo]                       [nvarchar](255) NULL,
  [OneUpManager]                          [nvarchar](255) NULL,
  [TwoUpEmployeeNo]                       [nvarchar](255) NULL,
  [TwoUpManager]                          [nvarchar](255) NULL,
  [corporationCode]                       [nvarchar](255) NULL,
  [corporationName]                       [nvarchar](255) NULL,
  [mainWorkAddressStreet]                 [nvarchar](255) NULL,
  [mainWorkAddresssuburbCity]             [nvarchar](255) NULL,
  [mainWorkAddressPostCode]               [nvarchar](255) NULL,
  [mainWorkAddressStateTerritory]         [nvarchar](255) NULL,
  [mainWorkAddressCountry]                [nvarchar](255) NULL,
  [telephoneNo]                           [nvarchar](255) NULL,
  [mobileNo]                              [nvarchar](255) NULL,
  [legalAddressStreet]                    [nvarchar](255) NULL,
  [legalAddressSuburbCity]                [nvarchar](255) NULL,
  [legalAddressPostCode]                  [nvarchar](255) NULL,
  [legalAddressStateTerritory]            [nvarchar](255) NULL,
  [nominatedMailingAddressStreet]         [nvarchar](255) NULL,
  [nominatedMailingAddressSuburbCity]     [nvarchar](255) NULL,
  [nominatedMailingAddressPostcode]       [nvarchar](255) NULL,
  [nominatedMailingAddressStateTerritory] [nvarchar](255) NULL,
  [emailAddress]                          [nvarchar](255) NULL,
  [userID]                                [nvarchar](255) NULL,
  [loadDateTime]                          [datetime] NULL,
  [empType]                               [nvarchar](255) NULL,
  [recordStatus]                          [nvarchar](5) NULL
);
GO
